In [1]:
import pandas as pd
import numpy as np


In [2]:
naveen = pd.read_csv("/content/drive/MyDrive/Iris.csv")
naveen

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [3]:
import sys
!{sys.executable} -m pip install sklearn

In [4]:
x =naveen.iloc[:,1:5].values

In [5]:
y = naveen.iloc[:,5].values

In [6]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
from sklearn.preprocessing import LabelEncoder 
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.linear_model import LogisticRegression
logmodal = LogisticRegression()
logmodal.fit(x_train,y_train)



LogisticRegression()

In [13]:
y_prad = logmodal.predict(x_test)

In [14]:
y_prad

array([0, 2, 0, 1, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 2, 1, 1, 1, 0, 2,
       2, 1, 1, 1, 2, 0, 1, 0])

In [15]:
y_test

array([0, 2, 0, 1, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 2, 1, 1, 1, 0, 2,
       2, 1, 1, 1, 2, 0, 1, 0])

In [16]:

import sys
!{sys.executable} -m pip install sklearn


In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_prad)


array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 12]])

In [18]:
28/30

0.9333333333333333

In [19]:
# k nearest algorithm work on nearest point which is nearset to the neighobrs
#p=2 is eculear distance p=1 maritime distance


In [20]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [21]:
y_prad = classifier_knn.predict(x_test)

In [22]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 12]])

In [23]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [24]:
y_prad = classifier_nb.predict(x_test)


In [25]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  1, 11]])

In [26]:
# support vector machine(SVM) algorithm in this algorithm lots of kernel sigmoid, linear,plynomial,
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel="sigmoid")
classifier_svm_sigmoid.fit(x_train,y_train)



SVC(kernel='sigmoid')

In [27]:
# as per the prediction all flowers comes in  one category in one column after devidation our prediction is not good
y_prad = classifier_svm_sigmoid.predict(x_test)

In [28]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [10,  0,  0],
       [12,  0,  0]])

In [29]:
8/30

0.26666666666666666

In [30]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)


SVC(kernel='linear')

In [31]:
y_prad = classifier_svm_linear.predict(x_test)

In [32]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 12]])

In [33]:
29/30

0.9666666666666667

In [34]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)


SVC()

In [35]:
y_prad = classifier_svm_rbf.predict(x_test)

In [36]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 12]])

In [37]:
29/30

0.9666666666666667

In [38]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [39]:
y_prad = classifier_svm_poly.predict(x_test)

In [40]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 12]])

In [41]:
26/30

0.8666666666666667

In [42]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy') #entropy means measure of impurity which decide weather impurity is or not in our data
classifier_dt.fit(x_train, y_train)



DecisionTreeClassifier(criterion='entropy')

In [43]:
y_prad = classifier_dt.predict(x_test)

In [44]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  3,  9]])

In [45]:
27/30

0.9

In [46]:
# Random forest algorithm 

In [47]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy') #entropy means measure of impurity which decide weather impurity is or not in our data
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [48]:
y_prad= classifier_rf.predict(x_test)

In [49]:
confusion_matrix(y_test,y_prad)

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  3,  9]])

In [50]:
27/30

0.9